config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  
  root to: 'pages#home'

  resources :apartments 
  # end
  resources :tenants 
  resources :leases, only: [:new, :create, :destroy]
    # resources :apartments, only: [:index, :show]
  # end
  # resources :leases, only: [:new, :create, :destroy, :show]
  # resources :apartments do 
  #   resources :tenants, shallow: true, only: [:show, :index]
  #   resources :leases, shallow: true, only: [:new, :create, :destroy]
  # end 
  # resources :tenants do 
  #   resources :apartments, shallow: true, only: [:show, :index]
  #   resources :leases, shallow: true, only: [:new, :create, :destroy]
  # end 

  # resources :leases, shallow: true, only: [:new, :create, :destroy] do 
  #   resources :apartments, shallow: true 
  #   resources :tenants, shallow: true 
  # end 

end

app/models/tenant.rb
class Tenant < ApplicationRecord
    has_many :leases, dependent: :destroy
    has_many :apartments, through: :leases
    validates :age, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 18}
    validates :name, presence: true
    accepts_nested_attributes_for :leases
    default_scope {order(:name)}

    scope :homed, -> {Tenant.joins(:leases)}
    scope :homeless, -> {Tenant.joins("LEFT OUTER JOIN leases ON tenants.id = leases.tenant_id").where(:leases => {:id => nil})}
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
    before_action :find_tenant, only: %i[show edit update destroy ] 

    def index
        # display the tenant/s of the chosen apartment 
        @tenants = Tenant.all
    end

    def show 
        # @apartment = Apartment.find(params[:apartment_id])
        # @tenant = Tenant.find(params[:id])
        # redirect_to apartment_tenant_path(@tenant)
    end

    def new
        @tenant = Tenant.new
    end

    def create
        @tenant = Tenant.new(tenant_params)
        respond_to do |format|
            if @tenant.save
                format.html { redirect_to @tenant, notice: "tenant #{@tenant.name} (#{@tenant.age} y/o) successfully created."}
                format.json { render 'show', status: :created, location: @tenant}
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json  {render json: @listing.errors, status: :unprocessable_entity }
            end
        end
    end

    def edit

    end

    def update
        respond_to do |format|
            if @tenant.update(tenant_params)
                format.html { redirect_to @tenant, notice: "tenant successfully updated."}
                format.json { render 'show', status: :ok, location: @tenant}
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json  {render json: @listing.errors, status: :unprocessable_entity }
            end
        end

    end

    def destroy 
        @tenant.destroy
        respond_to do |format|
            format.html { redirect_to root_path, notice: "tenant #{@tenant.name} was successfully removed from the database." }
            format.json { head :no_content }
        end
    end

    private

    def find_tenant
        @tenant = Tenant.find(params[:id])
    end


    def tenant_params
        params.require(:tenant).permit(:age, :name)
    end
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/tenants/_form.html.erb
<%= form_with model: @tenant do |form| %>
<% if @tenant.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(@tenant.errors.count, "error") %> prohibited this apartment from being saved:</p>

      <ul>
        <% @tenant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
              </ul>
    </div>
  <% end %>
    
    <%= form.label :name %>
    <%= form.text_field :name, placeholder: "#{@tenant.name}" %>

    <%= form.label :age %>
    <%= form.number_field :age, placeholder: "#{@tenant.age}" %>

    <%= form.submit %>

<% end %>

app/views/tenants/edit.html.erb
<h1>Edit tenant info</h1>

<%= render 'form', tenant: @tenant %>

app/views/tenants/index.html.erb
<h1>Residents</h1>

<ul>
<% @tenants.each do |tenant| %>
   <li> <%= tenant.name %>
    <%= link_to "View details", tenant_path(tenant) %>
    </li>
<% end %> 
</ul>

<%= link_to "Add a new resident", new_tenant_path %>

app/views/tenants/new.html.erb
<h1>Create a new tenant</h1>

<%= render 'form' %>

app/views/tenants/show.html.erb
<h1>Tenant information </h1>
<%# Unit <%= @apartment.number %> 


<%# Unit <% @apartment.number %>
 <%# is currently occupied by:  %> 
<ul>
<li>Name:<%= @tenant.name %></li>
<li>Age: <%= @tenant.age %></li>

</ul>

<%# <%= link_to 'View lease information', edit_tenant_path(@tenant.id) %> 
<%= link_to 'Edit tenant', edit_tenant_path(@tenant) %> |
<%= link_to 'Delete tenant', tenant_path(@tenant.id), method: :delete, data: {confirm: "Are you sure?"} %> 