config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  
  root to: 'pages#home'

  resources :apartments 
  # end
  resources :tenants 
  resources :leases, only: [:new, :create, :destroy]
    # resources :apartments, only: [:index, :show]
  # end
  # resources :leases, only: [:new, :create, :destroy, :show]
  # resources :apartments do 
  #   resources :tenants, shallow: true, only: [:show, :index]
  #   resources :leases, shallow: true, only: [:new, :create, :destroy]
  # end 
  # resources :tenants do 
  #   resources :apartments, shallow: true, only: [:show, :index]
  #   resources :leases, shallow: true, only: [:new, :create, :destroy]
  # end 

  # resources :leases, shallow: true, only: [:new, :create, :destroy] do 
  #   resources :apartments, shallow: true 
  #   resources :tenants, shallow: true 
  # end 

end

app/models/apartment.rb
class Apartment < ApplicationRecord
    has_many :leases, dependent: :destroy
    has_many :tenants, through: :leases 
    
    # Ensure there is a number & it is an integer
    validates :number,
    presence: true,
    numericality: {only_integer: true} 
    accepts_nested_attributes_for :leases

    # Order the apartments by number
    default_scope { order('number') }

    # Return an apartment object for all apartments with leases.
    scope :not_vacant, -> {Apartment.joins(:leases)}

    # Return an apartment object for all apartments without leases.
    # scope :vacant, -> {Apartment.joins('LEFT OUTER JOIN leases ON (apartments.id = leases.apartment_id)').where('leases.apartment_id IS NULL')}
    scope :vacant, -> {Apartment.joins("LEFT OUTER JOIN leases ON apartments.id = leases.apartment_id").where(:leases => {:id => nil})}

end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
    before_action :find_apartment, only: %i[show edit update destroy ]

    def index
        @apartments = Apartment.all
        @occupied_apartments = @apartments.not_vacant
        @vacant_apartments = @apartments.vacant
    end

   

    def show
        if @apartment.tenants.count > 0 
            @tenants = get_tenants
            @vacancy = false
        else 
            @vacancy = true 
        end
        @lease = Lease.where(apartment_id: @apartment.id)
    end
    
    def new
        @apartment = Apartment.new
    end

    def create
        @apartment = Apartment.new(apartment_params)
        respond_to do |format|
            if @apartment.save
                format.html { redirect_to @apartment, notice: "Apartment #{@apartment.number} successfully created."}
                format.json { render 'show', status: :created, location: @apartment}
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json  {render json: @listing.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
            if @apartment.update(apartment_params)
                format.html { redirect_to @apartment, notice: "Apartment #{@apartment.number} successfully updated."}
                format.json { render 'show', status: :ok, location: @apartment}
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json  {render json: @listing.errors, status: :unprocessable_entity }
            end
        end

    end

    def destroy 
        @apartment.destroy
        respond_to do |format|
            format.html { redirect_to root_path, notice: "Apartment #{@apartment.number} was successfully removed from the database." }
            format.json { head :no_content }
        end
    end

    private

    def get_tenants
        tenants = []
        t = 0 
        @apartment.tenants.each do |tenant| 
            tenants << {
                name: @apartment.tenants[t].name,
                age: @apartment.tenants[t].age
            }
            t += 1
        end 
        return tenants
    end

    def find_apartment
        @apartment = Apartment.find(params[:id])
    end

    def apartment_params
        params.require(:apartment).permit(
            :number,
        )
    end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/views/apartments/_form.html.erb
<%= form_with model: @apartment do |form| %>
 <% if @apartment.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(@apartment.errors.count, "error") %> prohibited this apartment from being saved:</p>

      <ul>
        <% @apartment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
              </ul>
    </div>
  <% end %>

    <%= form.label :number %>
    <%= form.number_field :number, placeholder: "#{@apartment.number}" %>

    <%= form.submit %>

<% end %>

app/views/apartments/edit.html.erb
<h1>Edit apartment info</h1>

<%= render 'form', apartment: @apartment %>

app/views/apartments/index.html.erb
<h1>Apartments</h1>
<p>occupied</p>

<ul>
<% @occupied_apartments.each do |apartment| %>
   <li> <h3>Unit # <%= link_to "#{apartment.number}", apartment_path(apartment) %></h3>
    
    </li>

<% end %>
</ul>


<p>vacant</p>

<ul>
<% @vacant_apartments.each do |apartment| %>
   <li> <h3>Unit # <%= link_to "#{apartment.number}", apartment_path(apartment) %></h3>
    
    </li>

<% end %>
</ul>

<%= link_to "Create a new apartment", new_apartment_path %> 

app/views/apartments/new.html.erb
<h1>Create a new apartment</h1>

<%= render 'form' %>

app/views/apartments/show.html.erb
<h1>Apartment information</h1>

<h2>Unit <%= @apartment.number %></h2>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque consequuntur deleniti facilis, magni doloremque sed dicta fugit quas nulla vitae in fugiat dolorem nemo ad, quos, quis qui? Nobis molestiae dolore quasi unde fugit distinctio ducimus excepturi animi amet provident maxime fuga a sed repellat, aspernatur optio dolorum ex eaque.</p>


<% if !@vacancy %>
<ul>
    <% @tenants.each do |tenant| %>
        <li><%= tenant[:name] %> (<%= tenant[:age] %>)</li>
    <% end %>
    </ul>
<% else %>
    <h1>Apartment VACANT! Sign a new lease  <%= link_to "here", new_lease_path(@lease) %></h1>
<% end %>


<%= link_to "Edit Apartment", edit_apartment_path(@apartment) %> | <%= link_to "Delete Apartment", @apartment, method: :delete, data: {confirm: "Are you sure? This will delete the associated lease."}  %> | <%= link_to "End lease", lease_path, method: :delete, data: {confirm: "Are you sure? You will be charged early exit fees."} %>